-   id: clang-tidy
    name: clang-tidy
    description: ''
    entry: clang-tidy
    language: python
    'types_or': [c++, c, c#, objective-c]
    args: ["--format-style=file"]
    require_serial: false
    additional_dependencies: []
    minimum_pre_commit_version: '2.9.2'
