name: main
on:
  push:
    branches: [main]
  schedule:
  - cron: '55 8 1 * *'
  workflow_dispatch:

jobs:
  build:
    name: main
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v2
    - run: pip install pre-commit-mirror-maker
    - run: git config --global user.name 'Github Actions'
    - run: git config --global user.email '41898282+github-actions[bot]@users.noreply.github.com'
    - run: pre-commit-mirror . --language python --package-name clang-tidy  --id=clang-tidy --types-or c++ --types-or c --types-or 'c#'  --types-or 'objective-c' --args=--format-style=file
    - run: |
        git checkout -b update-branch-${{ github.run_id }}
        git add .
        git commit -m "Automated update"
        git push origin update-branch-${{ github.run_id }}
      env:
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Create Pull Request
      uses: peter-evans/create-pull-request@v5
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        commit-message: "Automated update"
        branch: update-branch-${{ github.run_id }}
        base: main
        title: "Automated update"
        body: "This is an automated update from GitHub Actions."
        delete-branch: true

